# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Extras
plugins:
  - jekyll-multiple-languages-plugin

languages: ["en-US", "pt-BR"]

# Server
source:         "."
destination:    ./docs
host:           0.0.0.0
port:           9001
url:            "https://alexanmtz.github.io/lucifer-msdos/"
repo:           "https://github.com/alexanmtz/lucifer-msdos"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - build/
  - Gemfile
  - Gemfile.lock
  - README.md

# Social
title:              Lucifer
description:        "An algorithm from hell"
authors:            "Alexandre Magno and an Unknown author"
current_version:            "0.2.7"
